### ISSUE TITLE
Cod sursă?

### ISSUE THREAD

**Issue by ovidiub13** [gov-ithub/RoadRo_Web#1]
Cum putem contribuii dacă nu există cod sursă?

**Comment by cristinamoga** [comment]
RoadRo e blocat, nu am facut pentru aplicatia web gandita pentru Politie mai multe decat la hackathon; daca vrei sa ajuti poti contribui la noua aplicatie ce o facem pentru Politie -> petitii IGPR pentru dispozitive mobile (https://github.com/gov-ithub/Petitii_IGPR_Mobile)
